[supervisord]
logfile=supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=supervisord.pid
nodaemon=false

[unix_http_server]
file=supervisor.sock

[supervisorctl]
serverurl=unix://supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:wa-bridge]
command=node server.js
directory=wa-bridge
autostart=true
autorestart=true
startretries=5
stdout_logfile=wa-bridge.out.log
stderr_logfile=wa-bridge.err.log
environment=NODE_ENV="production"

[program:flask-app]
command=flask-app/venv/bin/gunicorn -w 3 -b 0.0.0.0:5000 --timeout 120 app:app
directory=flask-app
autostart=true
autorestart=true
startretries=5
stdout_logfile=flask-app.out.log
stderr_logfile=flask-app.err.log
environment=FLASK_ENV="production"
